version: '3'

services:
  web:
    build: .
    command: ["python", "./myproject/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - my-postgres

  my-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
    driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/aicha/Desktop/againandagain/volume'
